name: 'Publish a Release'
description: 'Publish an existing draft release'
author: 'Stu Yarrow'
inputs:
  
  
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
